app = "parser-listener-01"
primary_region = "ams"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
